name: CI_ACTION

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 23.x  
  MONGO_URI: mongodb://localhost:27017/mnnn-test

jobs:
  backend:
    name: NestJS Backend
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7 
        ports:
          - 27017:27017
        options: --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 23
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Backend Dependencies (with Node.js 23 legacy peer deps)
      working-directory: ./backend
      run: npm install --legacy-peer-deps 

    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test
      env:
        DATABASE_URL: ${{ env.MONGO_URI }}
        NODE_ENV: test

  frontend:
    name: Next.js Frontend
    runs-on: ubuntu-latest
    needs: backend

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 23
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Frontend with Node.js 23 support
      working-directory: ./frontend
      run: |
        npm install --legacy-peer-deps
        npm install -D next@latest  # Ensure latest Next.js compatibility

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: http://localhost:3000