name: CI_ACTION

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 23.x  
  MONGO_URI: mongodb://localhost:27017/mnnn-test

jobs:
  backend:
    name: NestJS Backend
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7 
        ports:
          - 27017:27017
        options: --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 23
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Backend Dependencies (with Node.js 23 legacy peer deps)
      working-directory: ./backend
      run: npm install --legacy-peer-deps 

    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test
      env:
        DATABASE_URL: ${{ env.MONGO_URI }}
        NODE_ENV: test

  frontend:
  needs: backend 
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 23.x  
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./frontend
      run: |
        npm ci
        npm install next@latest react@latest react-dom@latest
        
    - name: Build project
      working-directory: ./frontend
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL || 'http://localhost:3000' }}
      run: npm run build